services:
    shopera-app:
        user: "1000:1000"
        build:
            context: .
            dockerfile: Dockerfile
        image: shopera-laravel-app
        container_name: shopera-app
        restart: unless-stopped
        volumes:
            - ./:/var/www:z
        networks:
            - global-network
            - shopera-internal

    shopera-web:
        image: nginx:alpine
        container_name: shopera-web
        restart: unless-stopped
        environment:
            - VIRTUAL_HOST=shopera.test,shopera.metraj.site
            - VIRTUAL_PORT=80
        volumes:
            - ./:/var/www:z
            - ./docker-compose/nginx:/etc/nginx/conf.d/:z
        networks:
            - global-network
            - shopera-internal

networks:
    shopera-internal:
        driver: bridge
    global-network:
        external: true
